config/routes.rb
Rails.application.routes.draw do

  root to: 'dashboards#index'
  resources :dashboards, :courses, :questions

  get '/show/questions' => 'questions#show'

  delete '/destroyTitle/questions/:id', to: 'questions#destroyTitle', as: 'destroyTitle'
  get '/viewQuestion/questions', to: 'questions#viewQuestion'
  get '/answerQuestion/questions', to: 'questions#answerQuestion', as: 'answerQuestion'
  post '/questions/saveScore/', to: 'questions#saveScore'
  get '/viewScore/questions', to: 'questions#viewScore', as: 'viewScore'

  # post '/questions/:id' => 'questions#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


	scope :score_num5, -> {where(score_num: 5)}
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :courses
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :title
  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
	belongs_to :question

end

app/models/title.rb
class Title < ApplicationRecord
	has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    @course = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to courses_path
    else
      render 'new'
    end
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      redirect_to edit_course_path(@course)
    end
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to courses_path
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:courseID, :course_name, :group_id)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end

  def show
  end

  def creat
  end

  def update
  end

  def destroy
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def show
		@title = Title.all
	end

	def viewQuestion
		@title = Title.all
	end

	def answerQuestion
		@score = Score.new
		@title = Title.all
	end

	def new
		@question = Question.new
		@title = Title.all
	end

	def saveScore
    # render plain: params.inspect
    params[:answer_quiz].each do |quiz|
      # puts "quiz_id ="+params[:answer_quiz][quiz].inspect + params[:answer_quiz][quiz].inspect
      # @data = Array.new({
      # @data ={
      #   question_id: quiz[11..-1],
      #   score_num: params[:answer_quiz][:"#{quiz}"]
      # }
      # puts @data
      # @score = Score.new({question_id: quiz[11..-1], score_num: params[:answer_quiz][:"#{quiz}"]})
      @title = Title.all
      @score = Score.new
      @score.question_id = quiz[11..-1]
      @score.score_num = params[:answer_quiz][:"#{quiz}"]

     @score.save

    end
    redirect_to viewScore_path
  end

  def viewScore
  	@title = Title.all
  end

  def create
    # render plain: params[:question].permit(:question_text).inspect
    # render plain:  params[:question][:numSec].inspect

    num = params[:question][:numberSec].count

    (1..num).each do |number|
    	@title = Title.new(title: params[:question][:"title#{number}"].to_s)
    	if @title.save
    		params[:question][:"question_text#{number}"].each do |qt|
    			@title.questions << Question.create(question_text: qt)
    		end

    	else
    		render 'new'
    	end
    end
    redirect_to show_questions_path
  end

  def update
    # render plain: params.inspect
    @question = Question.find(params[:id])
    @question.question_text = params[:question][:question_text]

    if @question.save
    	render json: {:status => "OK" }
    	flash[:notice] = 'update success'
    end

  end

  def destroy
  	@question = Question.find(params[:id])
  	if @question.destroy

  		redirect_to show_questions_path

  	else
  		redirect_to show_questions_path
  	end
  end

  # destroy title & questions
  def destroyTitle
  	@title = Title.find(params[:id])

  	if @title.questions.destroy(@title.questions)
  		@title.destroy

  		redirect_to show_questions_path
  	end
  end

  private

  def question_params
  	params.require(:question).permit(:id, :question_text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/courses/_form.html.erb
<div class="col-6 mx-auto">
  <%= form_with(model: course, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :courseID %>
    <%= form.text_field :courseID, id: :courseID, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :course_name %>
    <%= form.text_field :course_name, id: :course_name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :group_id %>
    <%= form.collection_select :group_id, Group.all, :id, :group_name, {},class: 'form-control' %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-primary">SAVE</button>
    <button type="reset" class="btn btn-warning">CANCEL</button>
  </div>
  <% end -%>
</div>

app/views/courses/edit.html.erb
<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<div class="float-right">
  <%= link_to( icon('fas','plus')+' Course', new_course_path , class: 'btn btn-primary') %>
</div>
<table class="table table-striped table-hover table-sm mw-100" >
  <caption>Course Data Table</caption>
  <thead class="bg-secondary text-center">
    <tr>
      <th>#</th>
      <th>CourseID</th>
      <th>CourseName</th>
      <th>GroupName</th>
      <th>Create Date</th>
      <th>#</th>
    </tr>
  </thead>
  <tbody class="text-center">
    <% num = 0 %>
    <% @course.each do |course| %>
    <tr>
      <td><%= num +=1 %></td>
      <td><%= course.courseID %></td>
      <td><%= course.course_name %></td>
      <td><%= course.group.group_name %></td>
      <td><%= course.updated_at.strftime("%d/%m/%Y %H:%M") %> </td>
      <td>
        <%= link_to( icon('fas',"pencil-alt"), edit_course_path(course), class: 'btn btn-warning btn-sm') %>
        <%= link_to( icon('fas',"trash-alt"), course, class: 'btn btn-danger btn-sm',  method: :delete, data: { confirm: 'Are you sure?' }) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<%= render 'form', course: @course  %>

app/views/dashboards/creat.html.erb
<h1>Dashboards#creat</h1>
<p>Find me in app/views/dashboards/creat.html.erb</p>

app/views/dashboards/destroy.html.erb
<h1>Dashboards#destroy</h1>
<p>Find me in app/views/dashboards/destroy.html.erb</p>

app/views/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>

app/views/dashboards/show.html.erb
<h1>Dashboards#show</h1>
<p>Find me in app/views/dashboards/show.html.erb</p>

app/views/dashboards/update.html.erb
<h1>Dashboards#update</h1>
<p>Find me in app/views/dashboards/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Requestionniare
		<%= params[:controller] %>
	</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<%= yield :script %>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light alert-info mb-2 pt-2 pb-2">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand row" href="/">ระบบประเมิน</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse pr-4" id="navbarSupportedContent">
				<ul class="nav navbar-nav  ml-auto">
					<li class="nav-item <%= (params[:controller] == 'dashboards') ? 'active':'' %>">
						<%= link_to icon('fas',"tachometer-alt")+' ทั่วไป ', root_path, class: 'nav-link', title: 'ทั่วไป' %>
					</li>
					<li class="nav-item <%= (params[:controller] == 'courses') ? 'active':'' %>">
						<%= link_to icon('fas', 'list')+' คอร์ส', courses_path, class: 'nav-link', title: 'คอร์ส' %>
					</li>
					<li class="nav-item <%= (params[:controller] == 'questions') ? 'active':'' %>">
						<%= link_to icon('fas',"question-circle")+' แบบสอบถาม', questions_path, class: 'nav-link', title: 'แบบสอบถาม' %>
					</li>
					<li class="nav-item <%= (params[:controller] == 'questions') ? 'active':'' %>">
						<%= link_to icon('fas',"tasks")+' ตอบแบบสอบถาม', answerQuestion_path, class: 'nav-link', title: 'ตอบแบบสอบถาม' %>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<% flash.each do |name, message| %>
	<p><i><%= " #{message}" %></i></p>
	<% end %>

	<div class="container-fluid col-11 bg-light pt-2 pb-2 pr-2 pl-3 rounded">
		<%= yield %>
	</div>

</body>

</html>

app/views/questions/all.html.erb
<%= form_for @question do |f| %>
  <div class="row col-12">
    <div class="col-11 mb-3">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
  </div>
  <%= f.submit %>
  <% end %>

app/views/questions/answerQuestion.html.erb
<div class="row col-12"  style="margin-top: 5px;padding: 20px 20px 20px 20px;">
  <h5> นักศึกษาประเมิณผู้สอน รายวิชา <i><u><?php echo $course_name; ?></u></i></h5>
</div>
<!-- /.row -->

<%= form_for @score, :url => {controller => 'questions', :action => 'saveScore'} do |f|%>
<table class="table table-striped rounded" border='1' >
  <thead >
    <tr class="text-center">
      <th rowspan="2" class='p-5'><h5> หัวข้อการประเมิน </h5></th>
      <th colspan="5"><h5>ความพึงพอใจ</h5></th>
    </tr>
    <tr class="text-center">
      <th>5 <br> (มากที่สุด)</th>
      <th>4 <br> (มาก)</th>
      <th>3 <br> (ปานกลาง)</th>
      <th>2 <br> (น้อย)</th>
      <th>1 <br> (น้อยที่สุด)</th>
    </tr>
  </thead>
  <tbody >
    <% num = 0 %>
    <% @title.each do |t| %>
    <% num+=1 %>
    <% if t.nil? %>
    <tr>
      <td colspan="6" class="text-center">  ===================== ไม่มีข้อมูล =====================  </td>
    </tr>
    <% else %>
    <tr>
      <td colspan="6">  <!-- title -->
        <b><h5> <%= "(#{num}.) " + t.title %></h5></b>
      </td>
    </tr>
    <!-- ./ start question -->
    <tr>
      <% numq = 0 %>
      <% t.questions.each do |qut| %>
      <% numq+= 1 %>
      <td class="pl-5">
        <%= qut.question_text %>
      </td>
      <td class="ml-auto text-center">
       <%#= f.hidden_field "#{qut.id}", name: "answer_quiz[id#{qut.id}]", value: "#{qut.id}"  %>
       <%= radio_button( 'answer_quiz', "answer_quiz#{qut.id}", "5", class: 'answer_quiz', id: "#{qut.id}", :style => "width:26px;height:26px;") %>
     </td>
     <td class="ml-auto text-center">
       <%#= f.hidden_field "#{qut.id}", name: "answer_quiz[id#{qut.id}]", value: "#{qut.id}"  %>
      <%= radio_button( 'answer_quiz', "answer_quiz#{qut.id}", "4", class: 'answer_quiz', id: "#{qut.id}", :style => "width:26px;height:26px;") %>
    </td>
    <td class="ml-auto text-center">
     <%#= f.hidden_field "#{qut.id}", name: "answer_quiz[id#{qut.id}]", value: "#{qut.id}"  %>
      <%= radio_button( 'answer_quiz', "answer_quiz#{qut.id}", "3", class: 'answer_quiz', id: "#{qut.id}", :style => "width:26px;height:26px;") %>
    </td>
    <td class="ml-auto text-center">
     <%#= f.hidden_field "#{qut.id}", name: "answer_quiz[id#{qut.id}]", value: "#{qut.id}"  %>
      <%= radio_button( 'answer_quiz', "answer_quiz#{qut.id}", "2", class: 'answer_quiz', id: "#{qut.id}", :style => "width:26px;height:26px;") %>
    </td>
    <td class="ml-auto text-center">
     <%#= f.hidden_field "#{qut.id}", name: "answer_quiz[id#{qut.id}]", value: "#{qut.id}"  %>
      <%= radio_button( 'answer_quiz', "answer_quiz#{qut.id}", "1", class: 'answer_quiz', id: "#{qut.id}", :style => "width:26px;height:26px;") %>
    </td>
  </tr>
  <% end %> <!-- end each Titile.questions -->
  <% end %>  <!-- end if -->
  <% end %>  <!-- end each title-->
  <!-- ./end question -->
</tbody>
</table>
<div class="col-12 text-center">
  <%= link_to( icon('fas','reply')+" กลับ", questions_path , class: 'btn btn-warning') %>
  <%= button_tag( icon('fas','save')+" บันทึก",{:name => 'submit', :id => 'submit', :type => "submit", :class => 'btn btn-success', :action => 'create'}) %>
  <%= button_tag( icon('fas','times')+" ยกเลิก", { :name => 'reset', :id => 'reset', :type => 'reset', :class => 'btn btn-danger'}) %>
</div>

<% end %> <!-- end form -->

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/index.html.erb
<h1>จัดการแบบสอบถาม</h1>
<div class="card-deck text-center col-12 " >

	<div class="col-3 mt-4 mb-4">
		<div class="card w-100" >
			<div class="card-body">
				<%= icon('fas', 'list-ol fa-3x') %>
				<%= link_to "สร้างแบบประเมิน", new_question_path , class: 'card-title row justify-content-center h5', title: 'create requestion' %>
				<!-- <a href="<?php echo base_url('index.php/quiz/quiz_teacher'); ?>">
					<h5 class="card-title row justify-content-center"> สร้างแบบประเมินผู้สอน </h5>
				</a> -->
			</div>
		</div>
	</div>
	<!-- /.card col-3 -->

	<div class="col-3 mt-4 mb-4">
		<div class="card w-100" >
			<div class="card-body">
				<%= icon('far', 'edit fa-3x') %>
				<%= link_to "แก้ไขแบบประเมิน",  show_questions_path , class: 'card-title row justify-content-center h5', title: 'edit question' %>
				<%#= link_to "แก้ไขแบบประเมิน", questions_path , class: 'card-title row justify-content-center h5', title: 'edit requestion' %>
				<!-- <a href="<?php echo base_url('index.php/quiz/quiz_teacher'); ?>">
					<h5 class="card-title row justify-content-center"> สร้างแบบประเมินผู้สอน </h5>
				</a> -->
			</div>
		</div>
	</div>
	<!-- /.card col-3 -->

	<div class="col-3 mt-4 mb-4">
		<div class="card w-100" >
			<div class="card-body">
				<%=  icon('far', "list-alt fa-3x" )  %>
				<%= link_to("ดูแบบประเมิน", viewQuestion_questions_path , class: 'card-title row justify-content-center h5', title: 'view requestion') %>
				<!-- <i class="fas fa-list-ol"></i>
				<a href="<?php echo base_url('index.php/quiz/quiz_teacher'); ?>">
					<h5 class="card-title row justify-content-center"> สร้างแบบประเมินผู้สอน </h5>
				</a> -->
			</div>
		</div>
	</div>
	<!-- /.card col-3 -->

	<div class="col-3 mt-4 mb-4">
		<div class="card w-100" >
			<div class="card-body">
				<%=  icon('fas', "star fa-3x" )  %>
				<%=  icon('fas', "star fa-3x" )  %>
				<%=  icon('fas', "star fa-3x" )  %>
				<%= link_to("ดูคะแนนประเมิน", viewScore_path , class: 'card-title row justify-content-center h5', title: 'assessment score') %>
				<!-- <i class="fas fa-list-ol"></i>
				<a href="<?php echo base_url('index.php/quiz/quiz_teacher'); ?>">
					<h5 class="card-title row justify-content-center"> สร้างแบบประเมินผู้สอน </h5>
				</a> -->
			</div>
		</div>
	</div>
	<!-- /.card col-3 -->

</div>

app/views/questions/show.html.erb
<%# content_for :script, javascript_include_tag(:"/questions/question") %>


<div class="content" style="margin-top: 5px;padding: 20px 20px 20px 20px;">
	<h4> สร้างแบบสอบถาม </h4>
	<hr>
<!--=================================
=           Start Form              =
==================================-->

<%= form_for :question do |f| %>

<% num = 0 %>
<% @title.each do |t| %>

<div class="row col-12">
	<div class="col-11 mb-3">
		(<%= num+=1 %>)
		<%= f.label :'หัวข้อ/เรื่อง', class: 'font-weight-bold' %>
		<%= f.text_field :title, class: 'form-control',value: t.title, id: "title#{num}" %>
	</div>
	<div class="col-1">
		<%= link_to( icon('fas','trash-alt fa-2x'), destroyTitle_path(t), class: 'btn btn-danger mt-4', method: :delete, data: { confirm: 'ถ้าลบหัวข้อ คำถามก็จะถูกลบตามไปด้วย!!' }) %>
	</div>
</div>
<% numq = 0 %>
<% t.questions.each do |qut| %>
<% numq+= 1 %>
<div class="quiz" id='<%= "quiz#{num}_#{numq}" %>'>
	<div class="row pl-5">
		<div class="col-10 mb-3">
			<%= f.label :" #{num}.#{numq} คำถาม ?", class: 'font-weight-bold text-muted' %>
			<%= f.text_field :question, class: 'form-control',value: qut.question_text, id: "question#{qut.id}" %>
		</div>
		<div class="col-1">
			<%= link_to( icon('fas','trash-alt fa-2x'), qut, class: 'btn btn-warning mt-4',  method: :delete,data: { confirm: 'ต้องการลบคำถาม?' }) %>
		</div>
		<div class="col-1">
			<%= button_tag icon('fas','edit fa-2x'), class: 'btn btn-success mt-4 btn_edit', type: 'button', name: "edit_#{qut.id}", data:{edit_id: qut.id}  %>
		</div>
	    <!--
	    <div class="col-1">
	    <label for="" >&nbsp;</label>
	    <button type="button" class="form-control btn btn-primary addquestion" id="addQuestion0"><i class="fas fa-plus" aria-hidden='true'></i></button>
	    </div>
	  -->
	</div>

	<!-- <div id="ShowaddQuestion0" class="ShowaddQuestion">
	</div> -->
	<!-- /#showAddQuiz.showAddQuiz -->
</div>
<% end %>

<hr>
<!-- /.quiz -->
<% end %>
<% end %>
<!--==============================
=            End Form            =
===============================-->

</div>
<%= content_for :script do %>
	<script type="text/javascript">
		$(document).ready(function(){
			$('.btn_edit').click(function(){
				var dataId = $(this).data('edit-id');
				var dataValue = 	$('#question'+$(this).data('edit-id')).val();

				$.ajax({
					type: 'PUT',
					url: '/questions/'+dataId,
					dataType: 'json',
					data: JSON.stringify({
						  question: { id: dataId, question_text: dataValue },
					}),
					headers:{
						'Content-Type': 'application/json',
						'X-CSRF-Token': Rails.csrfToken()
					},
					success: function(resp){
						alert("บันทึกข้อมูลเรียบร้อย");
					},
					error:function(err){
						alert("เกิดข้อผิดพลาด");
					}

				});

			});
		});
	</script>
<% end %>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>

app/views/questions/viewQuestion.html.erb
<div class="row col-12"  style="margin-top: 5px;padding: 20px 20px 20px 20px;">
  <h5> นักศึกษาประเมิณผู้สอน รายวิชา <i><u><?php echo $course_name; ?></u></i></h5>
</div>
<!-- /.row -->

<!-- <form id='formQuiz' action="<?php echo base_url().$this->layout.'submitScroll'; ?>" method="post" accept-charset="utf-8"> -->
  <table class="table table-striped rounded" border='1' >
    <thead >
      <tr class="text-center">
        <th rowspan="2" class='p-5'><h5> หัวข้อการประเมิน </h5></th>
        <th colspan="5"><h5>ความพึงพอใจ</h5></th>
      </tr>
      <tr class="text-center">
        <th>5 <br> (มากที่สุด)</th>
        <th>4 <br> (มาก)</th>
        <th>3 <br> (ปานกลาง)</th>
        <th>2 <br> (น้อย)</th>
        <th>1 <br> (น้อยที่สุด)</th>
      </tr>
    </thead>
    <tbody >
      <% num = 0 %>
      <% @title.each do |t| %>
      <% num+=1 %>
      <% if t.nil? %>
      <tr>
        <td colspan="6" class="text-center">  ===================== ไม่มีข้อมูล =====================  </td>
      </tr>
      <% else %>
      <tr>
        <td colspan="6">  <!-- title -->
          <b><h5> <%= "(#{num}.) " + t.title %></h5></b>
        </td>
      </tr>
      <!-- ./ start question -->

      <tr>
        <% numq = 0 %>
        <% t.questions.each do |qut| %>
        <% numq+= 1 %>
        <td class="pl-5">
          <%= qut.question_text %>
        </td>
        <td class="ml-auto text-center">
          <%= radio_button(:"anwser_quiz#{qut.id}","", "5", class: 'answser_quiz', :disabled => 'disabled', :style => "width:26px;height:26px;") %>
        </td>
        <td class="ml-auto text-center">
          <%= radio_button(:"anwser_quiz#{qut.id}","", "4", class: 'answser_quiz', :disabled => 'disabled', :style => "width:26px;height:26px;") %>
        </td>
        <td class="ml-auto text-center">
          <%= radio_button(:"anwser_quiz#{qut.id}","", "3", class: 'answser_quiz', :disabled => 'disabled', :style => "width:26px;height:26px;") %>
        </td>
        <td class="ml-auto text-center">
          <%= radio_button(:"anwser_quiz#{qut.id}","", "2", class: 'answser_quiz', :disabled => 'disabled', :style => "width:26px;height:26px;") %>
        </td>
        <td class="ml-auto text-center">
          <%= radio_button(:"anwser_quiz#{qut.id}","", "1", class: 'answser_quiz', :disabled => 'disabled', :style => "width:26px;height:26px;") %>
        </td>
      </tr>
      <% end %> <!-- end each Titile.questions -->
      <% end %>  <!-- end if -->
      <% end %>  <!-- end each title-->
      <!-- ./end question -->
    </tbody>
  </table>
  <div class="col-12 text-center">

    <%= link_to( icon('fas','reply')+" กลับ", questions_path , class: 'btn btn-warning col-1') %>

    </div>
  <!-- </form> -->

app/views/questions/viewScore.html.erb
<div class="content viewscore" style="margin-top: 5px;padding: 20px 20px 20px 20px;">
	<!-- <div class=" col-12"> -->

		<h5>
			คะแนนประเมิน:  <i><u></u></i>
		</h5>
		<h5>
			จำนวนผู้ประเมิน: <u>  </u> คน
		</h5>
		<!-- </div> -->
		<!-- /.row -->

<!--  <table class="table table-striped rounded " border='1' >
	<thead > -->
		<hr class="mt-0"/>
		<div class="content col-12  table-responsive">
			<div class="pb-5 no-padding" id="button-tolls"></div>

			<table id="tableData" class="display table table-bordered table-sm text-sm font-weight-light" width="100%" cellspacing="0" style="font-size:13px;">
				<thead class="bg-light">
					<tr class="text-center">
						<th rowspan="2" class='p-5'><h5>ความรู้ความสามารถ  ทักษะ  และพฤติกรรม</h5></th>
					</tr>
					<tr class="text-center">
						<th>5 <br> (มากที่สุด)</th>
						<th>4 <br> (มาก)</th>
						<th>3 <br> (ปานกลาง)</th>
						<th>2 <br> (น้อย)</th>
						<th>1 <br> (น้อยที่สุด)</th>
					</tr>
				</thead>
				<%
				score5 = []
				score4 = []
				score3 = []
				score2 = []
				score1 = []
				%>
				<tbody >
					<% num = 0 %>
					<% @title.each do |t| %>
					<% num+=1 %>
					<% if t.nil? %>
					<tr>
						<td colspan="6" class="text-center">
							===================== ไม่มีข้อมูล =====================
						</td>
					</tr>
					<% else %>
					<tr>
						<td colspan="6">  <!-- title -->
							<b><h5> <%= "(#{num}.) " + t.title %></h5></b>
						</td>
					</tr>
					<!-- ./ start question -->

					<tr>
						<% numq = 0 %>
						<% t.questions.each do |qut| %>
						<% numq+= 1 %>
						<td class="pl-5">
							<%= qut.question_text %>
						</td>

						<td class="text-center">
							<%= num5 = qut.scores.select { |m| m.score_num == "5"}.count() %>
							<% score5.push(num5) %>
						</td>
						<td class="text-center">
							<%= num4 = qut.scores.select { |m| m.score_num == "4"}.count() %>
							<% score4.push(num4) %>
						</td>
						<td class="text-center">
							<%= num3 = qut.scores.select { |m| m.score_num == "3"}.count() %>
							<% score3.push(num3) %>
						</td>
						<td class="text-center">
							<%= num2 = qut.scores.select { |m| m.score_num == "2"}.count() %>
							<% score2.push(num2) %>
						</td>
						<td class="text-center">
							<%= num1 = qut.scores.select { |m| m.score_num == "1"}.count() %>
							<% score1.push(num1) %>
						</td>

					</tr>
					<% end %> <!-- end each Titile.questions -->
					<% end %>  <!-- end if -->
					<% end %>  <!-- end each title-->
					<tr class="alert-info text-dark" style="background-color: #e3f2fd;">
						<td class="text-center"><b>รวม</b></td>
						<td class="text-center"><b> <%= score5 != nil ? score5.sum : 0 %></b></td>
						<td class="text-center"><b> <%= score4 != nil ? score4.sum : 0 %></b></td>
						<td class="text-center"><b> <%= score3 != nil ? score3.sum : 0 %></b></td>
						<td class="text-center"><b> <%= score2 != nil ? score2.sum : 0 %></b></td>
						<td class="text-center"><b> <%= score1 != nil ? score1.sum : 0 %></b></td>
					</tr>
					<!-- ./end question -->
				</tbody>


			</table>
		</div>
		<div class="col-12 mt-3 text-center">

			<%= link_to( icon('fas','reply')+" กลับ", questions_path , class: 'btn btn-warning col-1') %>

		</div>
	</div>
	<!-- </div> -->